name: spd-2023-moxsi-talk
channel:
- conda-forge
dependencies:
- pip:
  - snakemake
  - ndcube
  - dask
  - distributed
  - zarr
  - git+https://github.com/wtbarnes/mocksipipeline.git
  - git+https://github.com/wtbarnes/overlappy.git