import pathlib

configfile: "config.yaml"


rule sample_spectral_cube_to_overlappogram:
    input:
        pathlib.Path(config["spectral_data_dir"]) / 'p{frequency}' / 'spectra'
    output:
        pathlib.Path(config["results_dir"]) / 'p{frequency}' / 'overlappograms' / 'overlappogram_o{order}.fits'
    params:
        spectral_order=lambda wildcards: int(wildcards.order)
    script:
        "project_spectral_cubes.py"
        